clamav_version_pattern: ^1.4.38$
clamav_pipelines_repo: https://github.com/patrickhuber/clamav-pipelines.git
pivnet_token: ((pivnet_token))

opsman_domain_or_ip_address: ((opsman_domain_or_ip_address))
opsman_admin_username: ((opsman_admin_username))
opsman_admin_password: ((opsman_admin_password))
