clamav_version_pattern: ^1.4.38$

pivnet_token: ((pivnet_token))

opsman_domain_or_ip_address: ((opsman_domain_or_ip_address))
opsman_admin_username: ((opsman_admin_username))
opsman_admin_password: ((opsman_admin_password))