---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/bosh2-docker

inputs:
- name: clamav-addon
- name: clamav-pipelines
- name: pcf-bosh-creds

run:
  path: clamav-pipelines/tasks/apply-clamav/task.sh

params:
  DATABASE_MIRROR_IP:
